title: Senior Data Engineer
logo: "/images/data-analysis-logo.jpg?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
 Arthur is a data engineer with a back-end profile who has worked in an Agile environment for eight years, consistently transforming data into business value. He loves holding workshops to mentor junior data engineers and working in diverse teams. He has extensive experience performing remotely across multicultural and geographically distributed teams. Arthur always enjoys leveraging his various skills to advance his professional and personal growth. 
  <br><br>
  <a href="mailto:serviceit86@gmail.com">Contact email</a> 
  
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0