title: Senior Data Engineer
logo: "/images/data-analysis-logo.jpg?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  Agile environment 
  <br><br>
  <a href="mailto:serviceit86@gmail.com">Contact email</a> 
  
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0